package ArduinoML.sandbox;

/*Generated by MPS */


public class map_App {
  public static void main(String[] args) {
    System.out.println("Code Generated by ArduinoML");

    System.out.println(" pinMode(" + 12 + ", OUTPUT);");
    System.out.println(" pinMode(" + 8 + ", INPUT);");

  }
}
