package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Actuator = 0;
  public static final int App = 1;
  public static final int Brick = 2;
  public static final int Sensor = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL);
    builder.put(0x769bab6b038f4abbL, Actuator);
    builder.put(0x769bab6b038f5241L, App);
    builder.put(0x769bab6b038f4248L, Brick);
    builder.put(0x769bab6b038f4f1aL, Sensor);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
