package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptApp = createDescriptorForApp();
  /*package*/ final ConceptDescriptor myConceptBrick = createDescriptorForBrick();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActuator, myConceptApp, myConceptBrick, myConceptSensor);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.App:
        return myConceptApp;
      case LanguageConceptSwitch.Brick:
        return myConceptBrick;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Actuator", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4abbL);
    b.class_(false, false, false);
    // extends: ArduinoML.structure.Brick
    b.super_(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975220923");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "App", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f5241L);
    b.class_(false, false, true);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975222849");
    b.version(3);
    b.aggregate("bricks", 0x769bab6b038f5394L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L).optional(false).ordered(true).multiple(true).origin("8546613193975223188").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBrick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Brick", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975218760");
    b.version(3);
    b.property("pin", 0x769bab6b038f4933L).type(PrimitiveTypeId.INTEGER).origin("8546613193975220531").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Sensor", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4f1aL);
    b.class_(false, false, false);
    // extends: ArduinoML.structure.Brick
    b.super_(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975222042");
    b.version(3);
    return b.create();
  }
}
