package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptApp = createDescriptorForApp();
  /*package*/ final ConceptDescriptor myConceptBrick = createDescriptorForBrick();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  /*package*/ final EnumerationDescriptor myEnumerationSTATUS = new EnumerationDescriptor_STATUS();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptApp, myConceptBrick, myConceptSensor, myConceptState, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.App:
        return myConceptApp;
      case LanguageConceptSwitch.Brick:
        return myConceptBrick;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      case LanguageConceptSwitch.State:
        return myConceptState;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationSTATUS);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Action", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b0394a032L);
    b.class_(false, false, false);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975570482");
    b.version(3);
    b.property("status", 0x769bab6b0394a4b6L).type(MetaIdFactory.dataTypeId(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b0394a3efL)).origin("8546613193975571638").done();
    b.associate("actuator", 0x769bab6b0394a6e9L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4abbL).optional(false).origin("8546613193975572201").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Actuator", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4abbL);
    b.class_(false, false, false);
    // extends: ArduinoML.structure.Brick
    b.super_(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975220923");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "App", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f5241L);
    b.class_(false, false, true);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975222849");
    b.version(3);
    b.associate("init_state", 0x769bab6b0394bc56L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b039494cdL).optional(false).origin("8546613193975577686").done();
    b.aggregate("bricks", 0x769bab6b038f5394L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L).optional(false).ordered(true).multiple(true).origin("8546613193975223188").done();
    b.aggregate("state", 0x769bab6b0394bfe5L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b039494cdL).optional(false).ordered(true).multiple(true).origin("8546613193975578597").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBrick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Brick", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975218760");
    b.version(3);
    b.property("pin", 0x769bab6b038f4933L).type(PrimitiveTypeId.INTEGER).origin("8546613193975220531").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Sensor", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4f1aL);
    b.class_(false, false, false);
    // extends: ArduinoML.structure.Brick
    b.super_(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4248L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975222042");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "State", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b039494cdL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975567565");
    b.version(3);
    b.aggregate("actions", 0x769bab6b03949ad5L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b0394a032L).optional(true).ordered(true).multiple(true).origin("8546613193975569109").done();
    b.aggregate("transition", 0x769bab6b0394b741L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b0394ab51L).optional(false).ordered(true).multiple(false).origin("8546613193975576385").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Transition", 0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b0394ab51L);
    b.class_(false, false, false);
    b.origin("r:7ea55c1d-157c-4fd3-b8e3-1390314bc832(ArduinoML.structure)/8546613193975573329");
    b.version(3);
    b.property("status", 0x769bab6b0394adbaL).type(MetaIdFactory.dataTypeId(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b0394a3efL)).origin("8546613193975573946").done();
    b.associate("sensor", 0x769bab6b0394af1aL).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b038f4f1aL).optional(false).origin("8546613193975574298").done();
    b.associate("target", 0x769bab6b0394b254L).target(0x3a20e6b063a4d28L, 0xbe2e490ba391ab9aL, 0x769bab6b039494cdL).optional(false).origin("8546613193975575124").done();
    return b.create();
  }
}
